plugins/deep_algos/deep_classifier/Dockerfile
plugins/features/dshell_netflow_parser/Dockerfile
plugins/ml_algos/eval_dev_classifier/Dockerfile
plugins/ml_algos/port_classifier/Dockerfile
plugins/ml_algos/train_dev_classifier/Dockerfile

https://github.com/lukasmartinelli/hadolint/wiki/DL3009

best practices docker

---

poseidon/baseClasses/Rabbit_Base.py
poseidon/poseidonMain/poseidonMain.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/NorthBoundControllerAbstraction.py

Main and NBCA now use that class rather than have individual rabbit logic

create base rabbit class

---

.gitignore
notebooks/advesarial/sessionizer.py
plugins/heuristics/pcap_stats/pcap_stats.py
poseidon/baseClasses/Rabbit_Base.py
poseidon/poseidonMain/poseidonMain.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/NorthBoundControllerAbstraction.py

tabs are not spaces.

---

poseidon/poseidonMonitor/test_poseidonMonitor.py

Test creation: signal_handler #257 
just some tests

Test creation: signal_handler

---

poseidon/poseidonMonitor/test_poseidonMonitor.py

Test creation: rabbit_callback #243

rabbit_callback_test + disappeared during merging test added back

---

poseidon/poseidonMonitor/NorthBoundControllerAbstraction/test_NorthBoundControllerAbstraction.py

Test creation: get_endpoint_next #232

https://github.com/CyberReboot/poseidon/issues/232

---

poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/test_bcf.py

had 2 functions accidentally same name, removed during online merge, putting renamed function back in.

something jacked up. #327 fixed

---

poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/test_bcf.py

mirror_traffic done elsewhere, can just use mock return

Test creation:bcf.py: miror_ip #333

---

poseidon/poseidonMonitor/EndPoint.py
poseidon/poseidonMonitor/endPoint.py
poseidon/poseidonMonitor/test_EndPoint.py
poseidon/poseidonMonitor/test_endPoint.py

Made a new pull request since some checks failed, hope its better now.

Added EndPoint.py

---

poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/controllerproxy.py
poseidon/poseidonMonitor/poseidonMonitor.py
poseidon/poseidonMonitor/test_poseidonMonitor.py
requirements.txt

getting 100s of:
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
for now put in something to not print out the warnings.

the controller has a self signed cert, 

---

poseidon/poseidonMonitor/test_poseidonMonitor.py

forgot to update endpoint data..

https://github.com/CyberReboot/poseidon/issues/255

---

README.md

update readme to explain Makefile options, issue #349

explain makefile options

---

.dockerignore
poseidon/poseidonMonitor/poseidonMonitor.py
poseidon/poseidonMonitor/test_poseidonMonitor.py

.coveragerc is needed for Dockerfile.poseidon to build.

fixing the break.

---

poseidon/poseidonMonitor/test_poseidonMonitor.py

Test creation: schedule_job_reinvestiation #249

---

poseidon/poseidonMonitor/NorthBoundControllerAbstraction/NorthBoundControllerAbstraction.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/bcf.py
poseidon/poseidonMonitor/poseidonMonitor.py

removed a couple of print statements, switched the event loop to print out in info

updated logging messages

---

README.md

update readme for running poseidon in vent

---

Dockerfile.poseidon

fix tini and python for alpine changes

---

helpers/posCliGui.py
poseidon/baseClasses/Monitor_Action_Base.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/NorthBoundControllerAbstraction.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/bcf.py
poseidon/poseidonMonitor/poseidonMonitor.py
poseidon/poseidonMonitor/test_poseidonMonitor.py

start_vent_collector was not fully covered, try-except was hiding some failures.

more coverage

---

Dockerfile.docs

Replace deprecated MAINTAINER with LABEL

---

poseidon/poseidonMonitor/endPoint.py
poseidon/poseidonMonitor/test_endPoint.py

additional field, and time

---

.plugin_config.yml
README.md
poseidon.template

https://github.com/shazow/urllib3/issues/1267

update to lowercase due to urllib3 bug

---

requirements.txt

Reverts CyberReboot/poseidon#633

Revert "Update pyyaml to 4.1"

---

README.md
helpers/run
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/UpdateSwitchState.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/bcf.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/sample_span_fabric.json
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/sample_span_fabric2.json
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/sample_state.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/test_bcf.py
poseidon/poseidonMonitor/NorthBoundControllerAbstraction/test_NorthBoundControllerAbstraction.py

399 interface group

---

.travis.yml

trying to make travis work across forks

---

README.md

Issue: https://github.com/CyberReboot/poseidon/issues/797

Expand instructions for making code modifications

---

README.md

I have added an improvement in a sentence, and corrected the typo error

Rectify the typos

---

.travis.yml
Dockerfile.test
api/app/data.py
api/requirements.txt
poseidon/controllers/bcf/bcf.py
poseidon/controllers/faucet/faucet.py
test-requirements.txt
tests/test_bcf.py

fixes running tests locally as well

closes #893; closes #877; closes #876; closes #850

---

README.md

Enhanced BCF details and provided config example

Added more BCF details

---

README.md

Added notes about needing admin privs

Updated some more BCF requirements

---

poseidon/cli/cli.py

closes #1060; progress on #1053; closes #1057; closes #1056; progress on #1039; progress on #1058

lots of CLI updates

---

requirements.txt

Reverts CyberReboot/poseidon#1163

Revert "Update urllib3 to 1.24.2"

---

api/app/data.py
poseidon/cli/cli.py
poseidon/controllers/bcf/bcf.py
poseidon/controllers/faucet/parser.py
tests/test_bcf.py
tests/test_cli.py

adds vlan from the API to endpoint data and displays it instean of tenant fror BCF controllers.

1034 bcf vlan

---

configure
release/configuration.py
release/templates/bin_poseidon
release/templates/deb_control
release/templates/deb_postinst
release/templates/make
release/templates/readme

adds a set of scripts and associated template files to generate:
- Makefile
- READ.md
- VERSION
- bin/poseidon
- debian/control
- debian/postinst
using the versions of the various plugins defined in .vent_startup.yml
Closes #1165

Adds scripts for release process

---

README.md
release/templates/readme

from the list of supported distros

remove Ubuntu 18.10 (Cosmic Cuttlefish) 

---

bin/poseidon

provides url to add poseidon API as a datasource to CRViz rather than…
instructing users to use the "Poseidon Network" dropdown option.
Closes #1308

CRViz integration fix

---

poseidon/cli/cli.py
tests/test_cli.py

adds `output_format` flag for values "csv" and "json"

output format

---

api/app/data.py
poseidon/controllers/bcf/bcf.py
poseidon/controllers/faucet/faucet.py
poseidon/controllers/faucet/parser.py
poseidon/helpers/actions.py
poseidon/main.py
rules.yaml
tests/test_main.py

Add ability to apply ACLs by sending a rabbit message.

Rabbit acls

---

poseidon/main.py

use id to identify ip instead of ip to ensure singularity

switch from ip to id

---

README.md

Reference the wayback machine version of the page to bask in the glory.

rookie of the year page has been deleted

---

installers/debian/config
installers/debian/control

Catch this at install time as otherwise this can result in Poseidon not working because FaucetProxy can't parse the config.

Check that FAUCET mirror port specification is actually a JSON object.

---

release/templates/readme

`$` needs to be escaped as `$$`

fix issue with readme template

---

poseidon/helpers/endpoint.py
poseidon/main.py

Fix missing event_data in update_acl_history()
Fix tuple in automated ACL change
Reduce code duplication when mirroring/unmirroring.
Minor lint.

incremental refactor and ACL fixes

---

docker-compose.yaml
helpers/faucet/docker-compose-experimental.yaml
helpers/faucet/docker-compose.yaml
poseidon/cli/commands.py
poseidon/controllers/faucet/faucet.py
poseidon/main.py
tests/test_commands.py

close issues, work on compose files

---

Dockerfile
config/poseidon.config
poseidon/helpers/config.py
poseidon/helpers/log.py
test-requirements.txt

Check that controller_nic is a valid interface.
Default logger_level if not specified.

More generic checking of poseidon.config.

---

config/poseidon.config
poseidon/controllers/faucet/acls.py
poseidon/controllers/faucet/faucet.py
poseidon/controllers/faucet/helpers.py
poseidon/controllers/faucet/parser.py
tests/test_parser.py

(shouldn't change functionality)

refactor and add config options for future tunnel

---

api/requirements.txt

Reverts CyberReboot/poseidon#1636

Revert "Update dependency gevent to v20"

---

config/poseidon.config
poseidon/controllers/faucet/faucet.py
poseidon/main.py
tests/test_main.py

fix leak of mirror status going from networkml mirror->unknown, speed up rabbit message processing.

---

.github/workflows/test.yml
Dockerfile.test
Makefile
api/app/data.py
poseidon/controllers/faucet/parser.py
poseidon/helpers/redis.py
poseidon/main.py
test-requirements.txt
tests/test_api.py
tests/test_main.py
tests/test_redis.py
workers/workers.json

NetworkML and p0f can return results for multiple hosts

---

api/requirements.txt
requirements.txt
workers/requirements.txt

Reverts CyberReboot/poseidon#1681

Revert "Update dependency redis to v3.5.1"

---

poseidon/controllers/bcf/bcf.py
poseidon/controllers/faucet/faucet.py
poseidon/controllers/faucet/parser.py
poseidon/main.py
tests/test_main.py
tests/test_parser.py

Don't queue FAUCET events that are only going to be ignored to avoid a backlog.

Fix not ignoring non-L2_LEARN messages.

---

poseidon/controllers/faucet/parser.py
tests/test_parser.py

Also consolidate config writing/reading for future faucetagent integration.

Test that Poseidon can change FAUCET config to mirror a port on any configured switch.

---

Dockerfile

This reverts commit f17afaeba05ccf105c1eb75a7eaa3aa1c9b8ceed.

Revert "Install gNMI tools for future faucetagent support."

---

api/requirements.txt
bin/poseidon
poseidon/main.py
test_e2e.sh

Workaround for docker-api broken by same issue as https://github.com/googleapis/google-cloud-cpp/issues/5123.
[2020-09-24 08:22:21 +0000] [5531] [INFO] Booting worker with pid: 5531
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject

Allow install from local tarfile for testing.

---

poseidon/helpers/metadata.py
requirements.txt

Use dnspython so can tune timeout and access future async resolver.

---

test_e2e.sh

(solves a 1/10 flake on test startup)

link bounce after switch comes up, to ensure Poseidon notices hosts.

---

tests/test_e2e.sh

* due to delay in prometheus' polling of poseidon state, a capture could have
started before the test realized, meaning not enough data was sent within the
capture window.
* the test capture time (60s) was too slow in slower environments.

fix p0f-related e2e flakes, due to not enough data captured.

---

docker-compose.yaml
lib/poseidon_api/poetry.lock
lib/poseidon_api/pyproject.toml
lib/poseidon_cli/poetry.lock
lib/poseidon_cli/pyproject.toml
lib/poseidon_core/pyproject.toml

Waiting to see if renovate picks up the core change also.. in which case will rebase.

switch to 0.18.3.dev

---

renovate.json

This reverts commit 4a7241acc300b7aa4168d559dbba3edfd94cc36b.

Revert "attempt to restrict mend to using poetry 1.1.15."

---

.github/workflows/ci-test.yml
lib/poseidon_api/poetry.lock
lib/poseidon_api/pyproject.toml
lib/poseidon_cli/poetry.lock
lib/poseidon_cli/pyproject.toml

convert import of poseidon-core to be local.

Convert to Monorepo pattern
